### ISSUE TITLE
Add and delete run with no arguments crashes

### ISSUE THREAD

**Issue by yakultbottle** [AY2425S1-CS2113-W14-4/tp#149]
Test case:
"add" or "delete" with no arguments after. Both lead to an ungraceful crash of the program. 

This is probably due to this line in Parser.java:

```
String[] splitInput = input.split("\\s+");
...
String arguments = String.join(" ", Arrays.copyOfRange(splitInput, 1, splitInput.length));
```

In this case, there is no String at index 1 and above, so it returns null. And afterwards, add and delete are being called with:

```
case "add":
    parseAddItemCommand(arguments).execute(this.items, this.storage);
    break;
case "delete":
    parseDeleteItemCommand(arguments).execute(this.items, this.storage);
    break;
```

**Comment by cnivedit** [comment]
Program crashing is due to failure of assertions. Disabling assertions should ensure normal execution of the program.

**Comment by yakultbottle** [comment]
Tested, the program is indeed only crashing because assertions are enabled. Since assertions are disabled by default in .jar files, I will downgrade the severity of this bug.

![image](https://github.com/user-attachments/assets/2a88d2cd-020d-4ce8-aa8f-1e010bec8d5d)
