### ISSUE TITLE
[PE-D][Tester D] delete not working as intended in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-4/tp#175]
![截屏2024-11-08 下午4.17.19.png](https://raw.githubusercontent.com/kq2003/ped/main/files/2900a5b8-5dde-4304-a7c2-25e7ef666216.png)

After I added an item, quantity, and date as written in UG, it is not allowing me to delete it. But the command in help worked. So it is a UG issue.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: kq2003/ped#1

**Comment by cxc0418** [comment]
duplicated issue, update UG
