### ISSUE TITLE
[PE-D][Tester A] Delete product with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-4/tp#190]
![image.png](https://raw.githubusercontent.com/DucPhong135/ped/main/files/fc039ff3-c3c1-4235-bff9-c42fd83a9595.png)
When i try to delete product with the same name, I cannot decide what product will delete

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DucPhong135/ped#4

**Comment by cxc0418** [comment]
should specify how delete works with item of same name but different expiry date
