### ISSUE TITLE
[PE-D][Tester A] Function description not clear

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W14-4/tp#208]
![image.png](https://raw.githubusercontent.com/DucPhong135/ped/main/files/1c9d0b0c-7182-4778-bbff-b6b49a521563.png)
in the UG, the use function is not being descripted clearly

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: DucPhong135/ped#10

**Comment by yijiano** [comment]
#195
