### ISSUE TITLE
[PE-D][Tester A] Not handling case when orders is empty

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-4/tp#217]
![image.png](https://raw.githubusercontent.com/DucPhong135/ped/main/files/00e2509e-004d-4e61-a7fb-ef3e07f899d7.png)
when order is empty, there is no return message

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: DucPhong135/ped#14

**Comment by yijiano** [comment]
#187
