### ISSUE TITLE
[PE-D][Tester A] function available in help but not available in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W14-4/tp#220]
![image.png](https://raw.githubusercontent.com/DucPhong135/ped/main/files/388a0d8a-2ec0-4861-ae26-40bff8f0c13b.png)
this function transaction is available in help but not in UG

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: DucPhong135/ped#15

**Comment by yijiano** [comment]
Same as #214, closed.
